-- Más comun, poco control, se puede insertar manualmente y generar errores
CREATE TABLE users (
	user_id serial PRIMARY KEY,
	username VARCHAR(100)
);


-- En este caso, el identity se configuro para que funcione igual al ejercicio anterior(serial)
CREATE TABLE users2 (
	user_id INTEGER GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
	username VARCHAR(100)
);
-- Más control, no esta permitido manipular el user_id
CREATE TABLE users3 (
	user_id INTEGER GENERATED ALWAYS as IDENTITY PRIMARY KEY,
	username VARCHAR(100)
);
-- Más control, indicar en que secuencia empezar y incrementar.
CREATE TABLE users4 (
	user_id INTEGER GENERATED ALWAYS as IDENTITY (START WITH 100 INCREMENT BY 2) PRIMARY KEY,
	username VARCHAR(100)
);

-- Llave primary compusta
CREATE TABLE userDual(
	id1 int,
	id2 int,
	PRIMARY KEY (id1, id2)
);